//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unity.VisualScripting.Generated.PropertyProviders
{
	
	
	[global::Unity.VisualScripting.SerializedPropertyProviderAttribute(typeof(global::UnityEngine.LowLevelPhysics2D.PhysicsQuery.QueryFilter))]
	public class PropertyProvider_UnityEngine_LowLevelPhysics2D_PhysicsQuery_QueryFilter : Unity.VisualScripting.SerializedPropertyProvider<UnityEngine.LowLevelPhysics2D.PhysicsQuery.QueryFilter>
	{
	}
}
